### ISSUE TITLE
Update website tutorials for 2.0

### ISSUE THREAD

**Issue by skystrife** [meta-toolkit/meta#100]
(This should all be done in the develop branch of the website, btw.)

Should mention things like how to configure metadata in a `corpus.toml`, how to format `metadata.dat`, etc.

**Comment by mbonakda** [comment]
I'm trying to figure out how to setup indexing/search with metadata on the dev branch. Are all the relevant metadata-related files for one of sample datasets (ceeasus, bcancer) checked in? I see bcancer-metadata.txt and ceeaus-metadata.txt, but I don't see a metadata line in corpus.toml or a metadata.dat file which are referenced in the original issue here. 

I've been going through the code to try to back it out, but I thought I'd post here in case it's easy for you to give me quick guidance on how to set it up.

**Comment by smassung** [comment]
Here's my `config.toml`, using the 20 newsgroups dataset.

```toml
dataset = "20newsgroups"
corpus = "line.toml" # located inside dataset folder
forward-index = "20news-fwd"
inverted-index = "20news-inv"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!
```

Here's the simplest config file, located in the 20newsgroups directory in `prefix` (as before):

```toml
# file: line.toml                                                               
type = "line-corpus"
```

You can add metadata with the tab-separated `metadata.dat` file, where each column is a different field. A simple metadata file can just be a renamed `20newsgroups.dat.names`, where there is only one column corresponding to the name of a document.

Here's another one with only one column denoting the path:

```toml
# file: line.toml                                                               
type = "line-corpus"
encoding = "shift_jis"
metadata = [{name = "path", type = "string"}]
```

Hope that helps.
