### ISSUE TITLE
configuring list filter

### ISSUE THREAD

**Issue by jruizaranguren** [meta-toolkit/meta#80]
I have tried to add the following filter to a config.toml
```
[[analyzers.filter]]
    type = "list"
    filename = "../data/lemur-stopwords.txt"
````
but I'm getting token_stream_exception: what():  file required for list_filter config

How should I configure this filter?

**Comment by skystrife** [comment]
`filename` should just be `file`: https://github.com/meta-toolkit/meta/blob/master/src/analyzers/filters/list_filter.cpp#L104

Try this:

```toml
[[analyzers.filter]]
type = "list"
file = "../data/lemur-stopwords.txt"
```

Does that work?

**Comment by jruizaranguren** [comment]
Thanks for your fast response. Unfortunately I'm getting a new error. 

*terminate called after throwing an instance of 'meta::util::factory<meta::analyzers::filter_factory, meta::analyzers::token_stream, std::unique_ptr<meta::analyzers
::token_stream, std::default_delete<meta::analyzers::token_stream> >, cpptoml::table const&>::exception'
  what():  unrecognized identifier*

This is my complete analyzers section (I just want to replicate default chain in order to make following adjustements):

```
[[analyzers]]
method = "ngram-word"
ngram = 1
    [[analyzers.filter]]
    type = "icu-tokenizer"
    
    [[analyzers.filter]]
    type = "lowercase"
    
    [[analyzers.filter]]
    type = "alpha"
    
    [[analyzers.filter]]
    type = "length"  
    min = 2
    max = 35
    
    [[analyzers.filter]]
    type = "list"
    file = "../data/lemur-stopwords.txt"
    
    [[analyzers.filter]]
    type = "porter2_stemmer"
    
    [[analyzers.filter]]
    type = "empty_sentence"
```

**Comment by skystrife** [comment]
I'll make a change locally to make this error message a little better (to include the identifier that's not recognized).

Try the following config (based on https://github.com/meta-toolkit/meta/blob/master/src/analyzers/filters/porter2_stemmer.cpp#L16 and https://github.com/meta-toolkit/meta/blob/master/src/analyzers/filters/empty_sentence_filter.cpp#L15)

```toml
[[analyzers]]
method = "ngram-word"
ngram = 1
    [[analyzers.filter]]
    type = "icu-tokenizer"

    [[analyzers.filter]]
    type = "lowercase"

    [[analyzers.filter]]
    type = "alpha"

    [[analyzers.filter]]
    type = "length"  
    min = 2
    max = 35

    [[analyzers.filter]]
    type = "list"
    file = "../data/lemur-stopwords.txt"

    [[analyzers.filter]]
    type = "porter2-stemmer"

    [[analyzers.filter]]
    type = "empty-sentence"
```
